export const mockListings = [
    {
    listing_id: 1,
    title: "The Marshall Mathers LP",
    artist: "Eminem",
    price_cents: 6500,
    media: "https://upload.wikimedia.org/wikipedia/en/a/ae/The_Marshall_Mathers_LP.jpg",
    tracks: [
  "Public Service Announcement 2000",
  "Kill You",
  "Stan",
  "Paul (skit)",
  "Who Knew",
  "Steve Berman",
  "The Way I Am [Clean]",
  "The Real Slim Shady [Explicit]",
  "Remember Me?",
  "I'm Back",
  "Marshall Mathers",
  "Ken Kaniff (skit)",
  "Drug Ballad",
  "Amityville",
  "Bitch Please II",
  "Kim",
  "Under the Influence",
  "Criminal"
]

  },
  {
    listing_id: 2,
    title: "Madvillainy",
    artist: "MF Doom",
    price_cents: 3500,
    media: "https://upload.wikimedia.org/wikipedia/en/5/5e/Madvillainy_cover.png",
    tracks: [
  "Accordion",1,
  "Great Day",2,
  "All Caps",
  "Meat Grinder",
  "Fancy Clown",
  "Rhinestone Cowboy",
  "Money Folder",
  "Figaro",
  "Raid",
  "Eye",
  "Supervillain Theme",
  "The Illest Villains",
  "Shadows of Tomorrow",
  "Curls",
  "Operation Lifesaver aka Mint Test",
  "Strange Ways",
  "Outro",
  "Papermill",
  "Rainbows",
  "Hardcore Hustle",
  "Intro",
  "One Beer",
  "Bistro",
  "Sickfit",
  "Interlude",
  "Beat Grinder",
  "Can't Reform Em",
  "Figaro / Beat #222",
  "Savage Beast",
  "Stakes",
  "Roller Coaster Riders",
  "Cold One"
]

  },
  {
    listing_id: 3,
    title: "Black Sabbath: The Dio Years",
    artist: "Black Sabbath",
    price_cents: 4500,
    media: "https://upload.wikimedia.org/wikipedia/en/1/1b/SabbathDio.jpg",
    tracks: [
  "Neon Knights",
  "Lady Evil",
  "Heaven and Hell",
  "Die Young",
  "Lonely Is the Word",
  "The Mob Rules",
  "Turn Up the Night",
  "Voodoo",
  "Falling Off the Edge of the World",
  "After All (The Dead)",
  "TV Crimes",
  "I",
  "Children of the Sea (live)",
  "The Devil Cried",
  "Shadow of the Wind",
  "Ear in the Wall"
]
  },
  {
    listing_id: 4,
    title: "Confessions",
    artist: "Usher",
    price_cents: 4500,
    media: "https://upload.wikimedia.org/wikipedia/en/f/f7/Usher_-_Confessions_album_cover.png",
    tracks: [
  "Intro",
  "Yeah",
  "Throwback",
  "Confessions (Interlude)",
  "Confessions Part II - Confessions Special Edition Version",
  "Burn",
  "Caught Up",
  "Superstar (Interlude)",
  "Superstar",
  "Truth Hurts",
  "Simple Things",
  "Bad Girl",
  "That's What It's Made For",
  "Can U Handle It?",
  "Do It to Me",
  "Take Your Hand",
  "Follow Me",
  "Whatever I Want",
  "Confessions, Part 1"
]
  },
  {
    listing_id: 5,
    title: "The Chronic",
    artist: "Dr. Dre",
    price_cents: 4500,
    media: "https://upload.wikimedia.org/wikipedia/en/1/19/Dr.DreTheChronic.jpg",
    tracks: [
  "The Chronic (Intro)",
  "Fuck Wit Dre Day (And Everybody's Celebratin')",
  "Let Me Ride",
  "The Day the Niggaz Took Over",
  "Nuthin' but a 'G' Thang",
  "Deeez Nuuuts",
  "Lil' Ghetto Boy",
  "A Nigga Witta Gun",
  "Rat-Tat-Tat-Tat",
  "The $20 Sack Pyramid",
  "Lyrical Gangbang",
  "High Powered",
  "The Doctor's Office",
  "Stranded on Death Row",
  "The Roach (The Chronic Outro)",
  "Bitches Ain't Shit"
]
  },
  
  {
    listing_id: 6,
    title: "Elephant",
    artist: "The White Stripes",
    price_cents: 4500,
    media: "https://media.gq-magazine.co.uk/photos/65c62b0db4be5de0d4eb99fa/master/w_960,c_limit/00s_albums_01.jpg",
    tracks: [
  "Seven Nation Army",
  "Black Math",
  "There's No Home for You Here",
  "I Just Don't Know What to Do with Myself",
  "In the Cold, Cold Night",
  "I Want to Be the Boy to Warm Your Mother's Heart",
  "You've Got Her in Your Pocket",
  "Ball and Biscuit",
  "The Hardest Button to Button",
  "Little Acorns",
  "Hypnotize",
  "The Air Near My Fingers",
  "Girl, You Have No Faith in Medicine",
  "It's True That We Love One Another"
]

  },
  {
    listing_id: 7,
    title: "Survivor",
    artist: "Destiny's Child",
    price_cents: 4500,
    media: "https://upload.wikimedia.org/wikipedia/en/9/99/Destiny%27s_Child_%E2%80%93_Survivor.jpg",
    tracks: [
  "Independent Women Part I",
  "Survivor",
  "Bootylicious",
  "Nasty Girl",
  "Fancy",
  "Apple Pie à la Mode",
  "Sexy Daddy",
  "Perfect Man",
  "Independent Women Part II",
  "Happy Face",
  "Dance with Me",
  "My Heart Still Beats",
  "Emotion",
  "Brown Eyes",
  "Dangerously in Love",
  "The Story of Beauty",
  "Gospel Medley",
  "Outro (DC-3) Thank You"
]
  },
  {
    listing_id: 8,
    title: "Year of the Gentleman",
    artist: "Ne-Yo",
    price_cents: 4500,
    media: "https://upload.wikimedia.org/wikipedia/en/3/3e/Ne-Yo_-_Closer.jpg",
    tracks: [
  "Closer",
  "Nobody",
  "Single",
  "Mad",
  "Miss Independent",
  "Why Does She Stay",
  "Fade into the Background",
  "So You Can Cry",
  "Part of the List",
  "Back to What You Know",
  "Lie to Me",
  "Stop This World"
]
  },
  {
    listing_id: 9,
    title: "Until the End of Time",
    artist: "2Pac",
    price_cents: 4500,
    media: "https://upload.wikimedia.org/wikipedia/en/9/94/Untiltheend.jpg",
    tracks: [
  "Ballad of a Dead Soulja",
  "Fuck Friendz",
  "Lil' Homies",
  "Let Em Have It",
  "Good Life",
  "Letter 2 My Unborn",
  "Breathin",
  "Happy Home",
  "All Out",
  "Fuckin' with the Wrong Nigga",
  "Thug N U Thug N Me (Remix)",
  "Everything They Owe",
  "Until the End of Time",
  "M.O.B.",
  "World Wide Mob Figgaz",
  "Big Syke Interlude",
  "My Closest Roaddogz",
  "Niggaz Nature (Remix)",
  "When Thugz Cry",
  "U Don't Have 2 Worry",
  "This Ain't Livin",
  "Why U Turn on Me",
  "LastOnesLeft",
  "Thug N U Thug N Me",
  "Words 2 My First Born",
  "Let Em Have It(remix)",
  "Running on E",
  "When I get Free",
  "Until the End of Time (RP Remix)",
    ]
  },
  {
    listing_id: 10,
    title: "Speakerboxxx/The Love Below",
    artist: "OutKast",
    price_cents: 4800,
    media: "https://upload.wikimedia.org/wikipedia/en/5/54/Speakerboxxx-The_Love_Below.png",
    tracks: [
  "Intro",
  "GhettoMusick",
  "Unhappy",
  "Bowtie",
  "The Way You Move",
  "The Rooster",
  "Bust",
  "War",
  "Church",
  "Bamboo (Interlude)",
  "Tomb of the Boom",
  "E-Mac (Interlude)",
  "Knowing",
  "Flip Flop Rock",
  "Interlude",
  "Reset",
  "D-Boi (Interlude)",
  "Last Call",
  "Bowtie (Postlude)",
  "The Love Below (Intro)",
  "Love Hater",
  "God (Interlude)",
  "Happy Valentine's Day",
  "Spread",
  "Where Are My Panties? (Interlude)",
  "Prototype",
  "She Lives in My Lap",
  "Hey Ya!",
  "Roses",
  "Good Day, Good Sir (Interlude)",
  "Behold a Lady",
  "Pink & Blue",
  "Love in War",
  "She's Alive",
  "Dracula's Wedding",
  "The Letter (Interlude)",
  "My Favorite Things",
  "Take Off Your Cool",
  "Vibrate",
  "A Life in the Day of Benjamin André (Incomplete)"
]   
  },
  {
    listing_id: 11,
    title: "R&G (Rhythm & Gangsta): The Masterpiece",
    artist: "Snoop Dogg",
    price_cents: 4500,
    media: "https://i.scdn.co/image/ab67616d0000b273e803716268c173c3f9a0c057",
    tracks:[
        "(Intro) I Love to Give You Light",
        "Bang Out",
        "Drop It Like It's Hot (featuring Pharrell)",
        "Can I Get a Flicc Witchu (featuring Bootsy Collins)",
        "Ups & Downs (featuring Bee Gees)",
        "The Bidness",
        "Snoop D.O. Double G",
        "Let's Get Blown (featuring Pharrell)",
        "Step Yo Game Up (featuring Lil Jon and Trina)",
        "Perfect",
  "WBALLZ (Interlude)",
  "Fresh Pair of Panties On",
  "Promise I",
  "Oh No",
  "Can U Control Yo Hoe",
  "Signs",
  "I'm Threw Witchu",
  "Pass It Pass It",
  "Girl Like U",
  "No Thang on Me"
    ]
  },
  {
    listing_id: 12,
    title: "Music of the Sun",
    artist: "Rihanna",
    price_cents: 4500,
    media: "https://upload.wikimedia.org/wikipedia/en/6/6e/Rihanna_-_Music_of_the_Sun.png",
    tracks: [
  "Pon de Replay",
  "Here I Go Again",
  "If It's Lovin' that You Want",
  "You Don't Love Me (No, No, No)",
  "That La, La, La",
  "The Last Time",
  "Willing to Wait",
  "Music of the Sun",
  "Let Me",
  "Rush",
  "There's a Thug in My Life",
  "Now I Know",
  "Pon de Replay (Remix)"
]
  },

  // ==== 2010s Albums ====
  {
    listing_id: 13,
    title: "Random Access Memories",
    artist: "Daft Punk",
    price_cents: 4000,
    media: "https://upload.wikimedia.org/wikipedia/en/2/26/Daft_Punk_-_Random_Access_Memories.png",
    tracks: [
  "Give Life Back to Music",
  "The Game of Love",
  "Giorgio by Moroder",
  "Within",
  "Instant Crush",
  "Lose Yourself to Dance",
  "Touch",
  "Get Lucky",
  "Beyond",
  "Motherboard",
  "Fragments of Time",
  "Doin' it Right",
  "Contact"
    ]
  },
  {
    listing_id: 14,
    title: "Demon Days",
    artist: "Gorillaz",
    price_cents: 3500,
    media: "https://upload.wikimedia.org/wikipedia/en/d/df/Gorillaz_Demon_Days.PNG",
    tracks: [
  "Intro",
  "Last Living Souls",
  "Kids with Guns",
  "O Green World",
  "Dirty Harry",
  "Feel Good Inc",
  "El Mañana",
  "Every Planet We Reach is Dead",
  "November Has Come",
  "All Alone",
  "White Light",
  "Dare (radio edit",
  "Fire Coming Out of the Monkey's Head",
  "Dont Get Lost in Heaven",
  "Demon Days",
  "The Swagga",
    ]
  },
  {
    listing_id: 15,
    title: "To Pimp a Butterfly",
    artist: "Kendrick Lamar",
    price_cents: 2500,
    media: "https://upload.wikimedia.org/wikipedia/en/f/f6/Kendrick_Lamar_-_To_Pimp_a_Butterfly.png",
    tracks: [
  "Wesley's Theory",
  "For Free? (Interlude)",
  "King Kunta",
  "Institutionalized",
  "These Walls",
  "u",
  "Alright",
  "For Sale? (Interlude)",
  "Momma",
  "Hood Politics",
  "How Much a Dollar Cost",
  "Complexion (A Zulu Love)",
  "The Blacker the Berry",
  "The Blacker the Berry",
  "You Aint Gotta Lie(Momma Said)",
  "i[Explicit]",
  "Mortal Man"
    ]
  },
  {
    listing_id: 16,
    title: "The Fame",
    artist: "Lady Gaga",
    price_cents: 4500,
    media: "https://upload.wikimedia.org/wikipedia/en/d/dd/Lady_Gaga_%E2%80%93_The_Fame_album_cover.png",
    tracks: [
  "Just Dance",
  "LoveGame",
  "Paparazzi",
  "Poker Face",
  "Eh, Eh (Nothing Else I Can Say)",
  "Beautiful, Dirty, Rich",
  "The Fame",
  "Money Honey",
  "Starstruck",
  "Boys Boys Boys",
  "Paper Gangsta",
  "Brown Eyes",
  "I Like It Rough",
  "Summerboy",
  "Disco Heaven"
]

  },
  {
    listing_id: 17,
    title: "I Am... Sasha Fierce",
    artist: "Beyoncé",
    price_cents: 3200,
    media: "https://upload.wikimedia.org/wikipedia/en/4/44/Single_Ladies_%28Put_a_Ring_on_It%29_cover.png",
    tracks: [
  "If I Were a Boy",
  "Halo",
  "Disappear",
  "Broken-Hearted Girl",
  "Ave Maria",
  "Smash Into You",
  "Satellites",
  "That's Why You're Beautiful",
  "Single Ladies (Put a Ring on It)",
  "Radio",
  "Diva",
  "Sweet Dreams",
  "Video Phone",
  "Halo(Remix)",
  "Ego[Explicit]",
  "Scared of Lonely"
    ]
  },
  {
    listing_id: 18,
    title: "I Am The West",
    artist: "Ice Cube",
    price_cents: 4500,
    media: "https://upload.wikimedia.org/wikipedia/en/6/69/Ice_Cube_-_I_Am_The_West_%28Front_Cover%29.jpg",
    tracks: [
  "A Boy Was Conceived (intro)",
  "Soul on Ice",
  "Life in California",
  "She Couldn't Make It on Her Own",
  "Urbanian",
  "Y'all Know Who I Am",
  "To West Coast",
  "I Rep That West",
  "Drink the Kool-Aid",
  "No Country for Young Men",
  "It Is What It Is",
  "Hood Robbin'",
  "Your Money or Your Life",
  "Nothing Like L.A.",
  "All Day, Every Day",
  "Fat Cat",
  "Man vs. Machine",
  "Pros vs. Joes"
]

  },
  {
    listing_id: 19,
    title: "Scorpion",
    artist: "Drake",
    price_cents: 4500,
    media: "https://upload.wikimedia.org/wikipedia/en/9/90/Scorpion_by_Drake.jpg",
    tracks: [
  "Survival",
  "Nonstop",
  "Elevate",
  "Emotionless",
  "God's Plan",
  "I'm Upset",
  "8 Out Of 10",
  "Mob Ties",
  "Can't Take A Joke",
  "Sandra's Rose",
  "Talk Up",
  "Is There More",
  "Peak",
  "Summer Games",
  "Jaded",
  "Nice For What",
  "Finesse",
  "Ratchet Happy Birthday",
  "That's How You Feel",
  "Blue Tint",
  "In My Feelings",
  "Don't Matter To Me",
  "After Dark",
  "Final Fantasy",
  "March 14"
]

  },
  {
    listing_id: 20,
    title: "Lemonade",
    artist: "Beyoncé",
    price_cents: 4900,
    media: "https://upload.wikimedia.org/wikipedia/en/5/53/Beyonce_-_Lemonade_%28Official_Album_Cover%29.png",
    tracks: [
  "Pray You Catch Me",
  "Hold Up",
  "Don't Hurt Yourself",
  "Sorry",
  "6 Inch",
  "Daddy Lessons",
  "Love Drought",
  "Sandcastles",
  "Forward",
  "Freedom",
  "All Night",
  "Formation"
]

  },
  {
    listing_id: 22,
    title: "?",
    artist: "XXXTentacion",
    price_cents: 4500,
    media: "https://i.scdn.co/image/ab67616d0000b273806c160566580d6335d1f16c",
    tracks: [
  "Introduction (instructions)",
  "ALONE, PART 3",
  "Moonlight",
  "SAD!",
  "the remedy for a broken heart (why am I so in love)",
  "Floor 555",
  "NUMB",
  "infinity (888) (feat. Joey Bada$$)",
  "going down!",
  "Pain = BESTFRIEND (feat. Travis Barker)",
  "$$$ (feat. Matt Ox)",
  "love yourself (interlude)",
  "SMASH! (feat. PnB Rock)",
  "I don't even speak spanish lol",
  "changes",
  "Hope",
  "schizophrenia",
  "before I close my eyes"
]

  },
  {
    listing_id: 23,
    title: "Beauty Behind the Madness",
    artist: "The Weeknd",
    price_cents: 4500,
    media: "https://upload.wikimedia.org/wikipedia/en/b/bd/The_Weeknd_-_Beauty_Behind_the_Madness.png",
    tracks: [
  "Real Life",
  "Losers (feat. Labrinth)",
  "Tell Your Friends",
  "Often",
  "The Hills",
  "Acquainted",
  "Can't Feel My Face",
  "Shameless",
  "Earned It",
  "In the Night",
  "As You Are",
  "Dark Times (feat. Ed Sheeran)",
  "Prisoner (feat. Lana Del Rey)",
  "Angel"
]

  },
  {
    listing_id: 24,
    title: "Astroworld",
    artist: "Travis Scott",
    price_cents: 4100,
    media: "https://upload.wikimedia.org/wikipedia/en/4/4b/Travis_Scott_-_Astroworld.png",
    tracks: [
  "STARGAZING",
  "CAROUSEL",
  "SICKO MODE",
  "R.I.P. SCREW",
  "STOP TRYING TO BE GOD",
  "NO BYSTANDERS",
  "SKELETONS",
  "WAKE UP",
  "5% TINT",
  "NC-17",
  "ASTROTHUNDER",
  "YOSEMITE",
  "CAN'T SAY",
  "WHO? WHAT!",
  "BUTTERFLY EFFECT",
  "HOUSTONFORNICATION",
  "Coffee Bean"
    ]
  },
];
